# Site settings
title: "Sonu Singh"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sonu Singh"
resume_title:                   "Lead I - Product Engineering"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sonusingh200190@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 8553684490"
resume_contact_address:         "Pacifica Aurum Happiness Tower, Padur, Chennai"

resume_header_contact_info:     "Chennai • +91 8553684490 • sonusingh200190@outlook.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a results-driven Big Data Engineer and Lead Java Developer with extensive experience in developing scalable solutions for enterprise clients, I am passionate about leveraging cutting-edge technologies to drive business growth. With a deep knowledge of Java, Spring Boot, Apache Spark, Hadoop, AWS, Apache Kafka, Apache Kylin, and Trino, I have a proven track record of delivering high-quality solutions that exceed client expectations. My commitment to teamwork, attention to detail, and passion for staying ahead of industry trends make me an asset to any organization.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/isonusingh"
  resume_linkedin_url:          "https://www.linkedin.com/in/sonu-bigdata-developer/"
  resume_instagram_url:         "https://www.instagram.com/singhsonu.90"
  resume_website_url:           "https://isonusingh.github.io/resume"
  resume_medium_url:            "https://medium.com/@sonusingh-javatech"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
